version: "2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper-learn
    container_name: zookeeper-learn
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-b:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka-b
    container_name: kafka-b
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-b:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  psql-db:
    image: postgres:13.13
    hostname: psql-db
    container_name: psql-db
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: "root"

    volumes:
      - /Users/cynthiawong/docker_dev/volumes/db:/var/lib/postgresql/data



